name: linterna_chispeza
description: Linterna Chispeza

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  torch_light: ^1.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BabaPro
      fonts:
        - asset: assets/fonts/babapro.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"
  remove_alpha_ios: true